embeddings:
  path: /home/jx/projects/models/embeddings
  model_name: mxbai-embed-large-v1

pdf_folder: /home/jx/projects/law-docs

db_dir: /home/jx/projects/db/law-docs

vectorstore:
  chroma:
    db_name: "chroma_db"
    collection_name: "law-docs"
  qdrant:
    collection_name: "law-docs"

postprocessors:
  rerank:
    top_n: 7
    path: /home/jx/projects/models/
    model: ms-marco-MiniLM-L-12-v2

retrievers:
  vectara:
    similarity_top_k: 15
    n_sentences_before: 2
    n_sentences_after: 2
  summary_doc:
    similarity_top_k: 10
    verbose: true
  fusion:
    mode: reciprocal_rerank
    similarity_top_k: 10
    num_queries: 4
    use_async: true
